services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1  # No genera archivos .pyc
      - PYTHONUNBUFFERED=1  # Output sin buffer
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped