services:
  web:
    build: 
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./config.py:/app/config.py
      - ./run.py:/app/run.py
      - ./.flaskenv:/app/.flaskenv
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    command: flask run --host=0.0.0.0
    restart: unless-stopped
